deployment:
  tasks:
    - echo "Starting deployment..."
    - export NODE_ENV=production
    - cd /home/gkmvetje/mvetApp
    - npm install
    - npx sequelize-cli db:migrate
    - pm2 restart mvetApp || pm2 start /home/gkmvetje/mvetApp/server.js --name mvetApp
    - echo "Deployment completed."
